apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lh81b7l6j-nodejs 
  janus-idp.io/tekton: lh81b7l6j-nodejs
  backstage.io/kubernetes-id: lh81b7l6j-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lh81b7l6j-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml